[versions]
minSdk = "26"
targetSdk = "34"
compileSdk = "34"

kotlinCompilerExtensionVersion = "1.5.5"

coreKtx = "1.9.0"
appcompat = "1.6.1"
material = "1.10.0"
lifecycleKtx = "2.6.2"
activityCompose = "1.8.1"
composeBom = "2023.10.01"
navigation = "2.7.5"

koin = "3.5.0"
moshi = "1.14.0"
retrofitVersion = "2.9.0"
coil = "2.5.0"

junit = "4.13.2"
mockk = "1.13.8"
kotest = "5.7.2"
coroutines-test = "1.7.3"

androidGradlePlugin = "8.2.0"
androidKotlin = "1.9.20"

[libraries]
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-lifecycleCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleKtx" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-composeUi = { module = "androidx.compose.ui:ui" }
androidx-composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-composeMaterial = { module = "androidx.compose.material:material" }
androidx-composeMaterial3 = { module = "androidx.compose.material3:material3" }

koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinAndroidCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
moshiKotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofitMoshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofitVersion" }
# As we are not going to test UI, we use Coil default singleton.
# If we need DI, use `io.coil-kt:coil-base` instead and configure loader(s) ourselves.
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

test-junit4 = { module = "junit:junit", version.ref = "junit" }
test-koin-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }

[plugins]
android-application = { id = "com.android.application", version.ref="androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref="androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref="androidKotlin" }

[bundles]
compose = ["androidx-activityCompose", "androidx-composeUi", "androidx-composeUiGraphics",
    "androidx-composeUiToolingPreview", "androidx-composeMaterial3", "androidx-composeMaterial",
    "androidx-navigation-compose", "androidx-lifecycleCompose"]
retrofit = ["retrofit", "retrofitMoshiConverter"]
koin = ["koinAndroid", "koinAndroidCompose"]

test = ["test-junit4", "test-koin-junit4", "test-mockk", "test-kotest", "test-coroutines"]
