[versions]
minSdk = "26"
targetSdk = "34"
compileSdk = "34"

kotlinCompilerExtensionVersion = "1.5.2"

coreKtx = "1.9.0"
appcompat = "1.6.1"
fragmentKtx = "1.6.2"
constraintlayout = "2.1.4"
swipeRefreshLayout = "1.1.0"
material = "1.10.0"
lifecycleExtensions = "2.2.0"
lifecycleKtx = "2.6.2"
activityCompose = "1.8.0"
composeBom = "2023.03.00"
navigation = "2.7.5"

koin = "3.5.0"
moshi = "1.14.0"
retrofitVersion = "2.9.0"
coil = "2.5.0"

junit = "4.13.2"
mockk = "1.13.8"
kotest = "5.7.2"
coroutines-test = "1.7.3"

androidGradlePlugin = "8.1.2"
androidKotlin = "1.8.10"

[libraries]
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-swipeRefreshLayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycleLivedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx" }
androidx-lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-composeUi = { module = "androidx.compose.ui:ui" }
androidx-composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-composeMaterial3 = { module = "androidx.compose.material3:material3" }
androidx-navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigationSafeargsPlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }

koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
moshiKotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofitMoshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofitVersion" }
# As we are not going to test UI, we use Coil default singleton.
# If we need DI, use `io.coil-kt:coil-base` instead and configure loader(s) ourselves.
coil = { module = "io.coil-kt:coil", version.ref = "coil" }

test-junit4 = { module = "junit:junit", version.ref = "junit" }
test-koin-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }

[plugins]
android-application = { id = "com.android.application", version.ref="androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref="androidKotlin" }
androidx-navigationSafeArgsKotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

[bundles]
lifecycle = ["androidx-lifecycleExtensions", "androidx-lifecycleRuntimeKtx", "androidx-lifecycleLivedataKtx", "androidx-lifecycleViewmodelKtx"]
compose = ["androidx-activityCompose", "androidx-composeUi", "androidx-composeUiGraphics", "androidx-composeUiToolingPreview", "androidx-composeMaterial3"]
navigation = ["androidx-navigationFragmentKtx", "androidx-navigationUiKtx"]
retrofit = ["retrofit", "retrofitMoshiConverter"]

test = ["test-junit4", "test-koin-junit4", "test-mockk", "test-kotest", "test-coroutines"]
